In [1]:
import numpy as np

# ABC Technologies-IT Consulting

Task 1: Read data from employee data file and find the average age of all the employees

In [2]:
#Converting csv file to an array
employee_data=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1).astype(int)

#Accessing Age column
x=employee_data[:,1]

#Calculation Average Age and storing in a avg_age variable
avg_age=np.sum(x)/np.size(x)

#Printing Average Age
print('{} is the average age of all the employees'.format(avg_age))

28.26 is the average age of all the employees


Task 2:Find total number of employees who are over 25 years old. Display such employees along with employee code

In [3]:
print('Total number of employees who are over 25 years old : ',(np.size(np.where(x>25))))
ind=x>25
a=employee_data[ind,0:2]
print(a)

Total number of employees who are over 25 years old :  38
[[ 2 27]
 [ 3 31]
 [ 4 29]
 [ 5 27]
 [ 6 26]
 [ 7 27]
 [ 9 27]
 [10 32]
 [11 28]
 [12 27]
 [14 27]
 [15 35]
 [16 33]
 [17 28]
 [20 27]
 [21 37]
 [22 27]
 [24 27]
 [25 28]
 [26 26]
 [27 27]
 [28 27]
 [29 29]
 [30 49]
 [31 26]
 [32 32]
 [33 26]
 [37 28]
 [38 28]
 [40 26]
 [41 32]
 [42 35]
 [43 33]
 [44 31]
 [45 30]
 [46 36]
 [49 32]
 [50 34]]


Task 3: Find total number of employeees whose age is in between 30 & 35 years. Display all such employees along with their employee code.

In [5]:
print('Total number of employees having age in between 30 & 35  :',np.size(np.where((x>30)&(x<35))))

ind=np.where ((x>30)&(x<35))

a=employee_data[ind,0:2]

print(a)

Total number of employees having age in between 30 & 35  : 9
[[[ 3 31]
  [10 32]
  [16 33]
  [32 32]
  [41 32]
  [43 33]
  [44 31]
  [49 32]
  [50 34]]]


# Axess-Customer Retention

Task 1: Identify customers whose spending score is more than 80.Find total number of such customers and display each of their details.

In [7]:
#Converting csv file to an array
shopping_data=np.genfromtxt('DS1_C4_S1_Shopping_Data_Challenge.csv',delimiter=',',skip_header=1).astype(int)

#Accessing spending score column
x=shopping_data[:,3]

#Identifying count of customers whose salary score is more than 80
print('Number of customers whose spending score is more than 80 : ',np.size(np.where(x>80)))
print(' ')

#Displaying Details of those customers
ind=np.where(x>80)
print('Details of customers :')
print(shopping_data[ind,0:4])

Number of customers whose spending score is more than 80 :  30
 
Details of customers :
[[[  2  21  15  81]
  [  8  23  18  94]
  [ 12  35  19  99]
  [ 20  35  23  98]
  [ 26  29  28  82]
  [ 30  23  29  87]
  [ 34  18  33  92]
  [ 36  21  33  81]
  [ 42  24  38  92]
  [124  39  69  91]
  [128  40  71  95]
  [136  29  73  88]
  [142  32  75  93]
  [144  32  76  87]
  [146  28  77  97]
  [150  34  78  90]
  [152  39  78  88]
  [156  27  78  89]
  [162  29  79  83]
  [164  31  81  93]
  [168  33  86  95]
  [174  36  87  92]
  [176  30  88  86]
  [180  35  93  90]
  [182  32  97  86]
  [184  29  98  88]
  [186  30  99  97]
  [190  36 103  85]
  [194  38 113  91]
  [200  30 137  83]]]


Task 2:Fetch the rows corresponding to ages between 20 and 24

In [8]:
#Storing index values
ind=np.where((x>19)&(x<25)) 

#Fetching details
shopping_data[ind,0:4]

array([[[149,  34,  78,  22],
        [153,  44,  78,  20],
        [167,  42,  86,  20],
        [187,  54, 101,  24],
        [191,  34, 103,  23]]])

Task 3: Find lowest and highest annual incomes & display their customer code
    
  

In [15]:
#Printing maximum and minimum annual income
print('Highest annual income : ',max(shopping_data[:,2]))
print('Lowest annual income : ',min(shopping_data[:,2]))

ind_1=np.where((shopping_data[:,2]==max(shopping_data[:,2]))) #index value for maximum annual income
ind_2=np.where((shopping_data[:,2]==min(shopping_data[:,2]))) #index value for minimum annual income


print(shopping_data[ind_1,0:3:2])  #Customer code of maximum annual income
print(shopping_data[ind_2,0:3:2])   #Customer code of minimum annual income


Highest annual income :  137
Lowest annual income :  15
[[[199 137]
  [200 137]]]
[[[ 1 15]
  [ 2 15]]]


Task 4: Fetch details of the customers whose spending score is more than 75 with a minimum annual salary of at least $35K and age less than 45. How many such customers are there.

In [10]:
print('Number of customers: ',np.size([np.where((shopping_data[:,3]>75)&(shopping_data[:,2]>=35)&(shopping_data[:,1]<45))]))

Number of customers:  26


Task 5: The company wishes to offer random discount coupons between 10% and 50% to all customers.Maintain a new column about discount details along with main data.

In [13]:
#Counting number of rows in original dataset
print(shopping_data.shape)
#200 numbers of rows in main dataset

#Creating additional column of discount_percentage
discount=np.random.randint(10,51,200,int).reshape(200,1)

#Adding one column in original dataset
shopping_data=np.append(shopping_data,discount,axis=1)
print(shopping_data)



(200, 5)
[[  1  19  15  39  33  30]
 [  2  21  15  81  19  14]
 [  3  20  16   6  42  26]
 ...
 [198  32 126  74  18  10]
 [199  32 137  18  43  11]
 [200  30 137  83  24  22]]


Task 6: Identify the customers who get discount more than 45% 

In [14]:
ind=np.where(shopping_data[:,5]>45)

print('The number of customers getting discount more than 45% : ',np.size(np.where(shopping_data[:,5]>45)))

print('Details of customers : ')
shopping_data[ind,0:5]

The number of customers getting discount more than 45% :  21
Details of customers : 


array([[[  5,  31,  17,  40,  43],
        [  8,  23,  18,  94,  39],
        [ 13,  58,  20,  15,  18],
        [ 21,  35,  24,  35,  13],
        [ 25,  54,  28,  14,  21],
        [ 35,  49,  33,  14,  21],
        [ 39,  36,  37,  26,  41],
        [ 40,  20,  37,  75,  18],
        [ 45,  49,  39,  28,  38],
        [ 55,  50,  43,  45,  16],
        [ 58,  69,  44,  46,  43],
        [ 67,  43,  48,  50,  35],
        [ 84,  46,  54,  44,  20],
        [ 92,  18,  59,  41,  45],
        [115,  18,  65,  48,  21],
        [127,  43,  71,  35,  32],
        [134,  31,  72,  71,  21],
        [153,  44,  78,  20,  31],
        [177,  58,  88,  15,  43],
        [183,  46,  98,  15,  45],
        [184,  29,  98,  88,  26]]])